(* mgtkgen --- generate wrapper code from .defs file.                       *)
(* (c) Ken Friis Larsen and Henning Niss 1999, 2000.                        *)

signature Messages =
sig

    val copyright: AST.target -> TextIO.outstream -> unit
    val autogenerated: AST.target -> TextIO.outstream -> unit
    val autostart: AST.target -> TextIO.outstream -> unit

end (* signature Messages *)

(*
   Structure Messages provides a few functions for generating comments
   in the generated files.

   [copyright target stream] print a copyright message to the output
   stream stream. The target argument determines the kind of comment
   generated. 

   [autogenerated target stream] print a message saying that the file
   is generated automatically to the output stream stream. The target
   argument determines the kind of comment generated.

   [autostart target stream] print a message containing the string
   AUTOMATICALLY (for easy reference), to indicate the beginning of
   the automatically generated code, to the output stream stream.
   The target argument determines the kind of comment generated.

*)