(* defs2sml --- generate wrapper code from .defs file.                      *)
(* (c) Ken Friis Larsen and Henning Niss 1999, 2000.                        *)

signature Messages =
sig

    val copyright: TextIO.outstream -> unit
    val autogenerated: TextIO.outstream -> unit
    val autostart: TextIO.outstream -> unit

end (* signature Messages *)

(*
   Structure Messages provides a few functions for inserting comments
   in the generated files.

   [copyright stream] print a copyright message to the output stream
   stream. The target option (see Main.sml) determines the kind of
   comment generated.

   [autogenerated stream] print a message saying that the file
   is generated automatically to the output stream stream. The target
   option determines the kind of comment generated.

   [autostart stream] print a message containing the string
   AUTOMATICALLY (for easy reference), to indicate the beginning of
   the automatically generated code, to the output stream stream.  The
   target option determines the kind of comment generated.

*)